/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group_13.ui;

/**
 *
 * @author JONIK
 */
public class MainFrame extends javax.swing.JFrame {

    private PatientPanel patientPanel;
    private RecordPanel recordPanel;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this.setTitle("Health Record System");
        initComponents();
        jSplitPane1.setResizeWeight(0.5);

        patientPanel = new PatientPanel();
        recordPanel = new RecordPanel();

        jSplitPane1.setLeftComponent(patientPanel);
        jSplitPane1.setRightComponent(recordPanel);

        patientPanel.setPatientSelectionListener(patient -> {
            recordPanel.showRecordsForPatient(patient);
            recordPanel.clearSelection();
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        patientPanel1 = new com.group_13.ui.PatientPanel();
        recordPanel1 = new com.group_13.ui.RecordPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jSplitPane1.setDividerLocation(508);
        jSplitPane1.setDividerSize(6);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setLeftComponent(patientPanel1);

        javax.swing.GroupLayout recordPanel1Layout = new javax.swing.GroupLayout(recordPanel1);
        recordPanel1.setLayout(recordPanel1Layout);
        recordPanel1Layout.setHorizontalGroup(
            recordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        recordPanel1Layout.setVerticalGroup(
            recordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(recordPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private com.group_13.ui.PatientPanel patientPanel1;
    private com.group_13.ui.RecordPanel recordPanel1;
    // End of variables declaration//GEN-END:variables
}
