/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.group_13.ui;

import java.util.*;
import com.group_13.model.*;
import com.group_13.service.PatientService;

import javax.swing.JOptionPane;

/**
 *
 * @author JONIK
 */
public class PatientPanel extends javax.swing.JPanel {

    private PatientTable model = new PatientTable(); // placeholder
    private Patient patient;
    private PatientSelectionListener listener;

    private static PatientPanel INSTANCE;

    public static synchronized PatientPanel getInstance() {
        if (INSTANCE == null) {
            INSTANCE = new PatientPanel();
        }
        return INSTANCE;
    }

    /**
     * Creates new form PatientPanel
     */
    private PatientPanel() {
        initComponents();
        jTable1.setModel(model);
        // loadTestData();

        jTable1.getSelectionModel().addListSelectionListener(e -> {

            if (!e.getValueIsAdjusting()) {

                int row = jTable1.getSelectedRow();

                if (row >= 0) {
                    Patient selected = model.getPatient(row);

                    firePatientSelected(selected);
                }
            }
        });

        jTable1.addMouseListener(
                new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        if (evt.getClickCount() == 2) { // double-click
                            int row = jTable1.getSelectedRow();
                            if (row >= 0) {
                                Patient selected = model.getPatient(row);
                                openPatientFrame(selected);
                            }
                        }
                    }
                });
    }

    private void openPatientFrame(Patient patient) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            PatientModifyFrame frame = new PatientModifyFrame(patient);
            frame.setVisible(true);
        });
    }

    private void firePatientSelected(Patient p) {
        if (listener != null) {
            listener.patientSelected(p);
            this.patient = p;
        }
    }

    public void setPatientSelectionListener(PatientSelectionListener l) {
        this.listener = l;
    }

    public void passQueryResults(Patient[] patientlist) {
        if (patientlist == null) {
            model.setPatients(new ArrayList<>());
            return;
        }
        List<Patient> list = new ArrayList<>(Arrays.asList(patientlist));
        model.setPatients(list);
    }

    public interface PatientSelectionListener {

        void patientSelected(Patient patient);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Create new Patient");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Delete patient");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton1.setText("Search patients");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Modify Patient");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575,
                                                Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton4)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton4)
                                        .addComponent(jButton3)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        javax.swing.SwingUtilities.invokeLater(() -> {
            PatientCreateFrame frame = new PatientCreateFrame();
            frame.setVisible(true);
        });
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        javax.swing.SwingUtilities.invokeLater(() -> {
            PatientSearchFrame frame = new PatientSearchFrame();
            frame.setVisible(true);
        });
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        if (patient == null) {
            // no patient selected
            JOptionPane.showMessageDialog(this,
                    "Please select a patient to update.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.SwingUtilities.invokeLater(() -> {
            PatientModifyFrame frame = new PatientModifyFrame(patient);
            frame.setVisible(true);
        });
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        if (patient == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select a patient to delete.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (patient.getId() == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot delete: patient ID is missing!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete patient " + patient.getFName() + " " + patient.getLName() + "?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Result<Void> result = PatientService.getInstance().deletePatient(patient);
                if (result.isSuccess()) {
                    JOptionPane.showMessageDialog(this,
                            "Patient deleted successfully.",
                            "Deleted",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Failed to delete patient!",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                model.deletePatient(patient);
                patient = null;

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error deleting patient: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }// GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
