package com.group_13.ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.group_13.service.PatientService;
import com.group_13.service.RecordService;
import com.group_13.model.Patient;
import com.group_13.model.Result;
/**
 * A frame for creating a new patient. Contains a PatientDataPanel for entering patient information and buttons for creating the patient or canceling the operation.
 * Calls PatientService to create the patient and updates the PatientPanel with the new patient on success.
 * @author JONIK
 */
public class PatientCreateFrame extends javax.swing.JFrame {
    
        private Patient patient;
        private PatientPanel panel;

    /**
     * Creates new form PatientCreateFrame
     */
    public PatientCreateFrame(PatientPanel panel) {
        this.panel = panel;
        initComponents();
        setTitle("Create new patient");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientDataPanel1 = new com.group_13.ui.PatientDataPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientDataPanel1.setMinimumSize(new java.awt.Dimension(500, 500));

        jButton1.setText("Create patient");
        jButton1.addActionListener(e -> {
            try {
                jButton1ActionPerformed(e);
            } catch (Exception g) {
                // TODO Auto-generated catch block
                g.printStackTrace();
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientDataPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientDataPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        patient = new Patient();
        patientDataPanel1.updatePatientData(patient);

        // disable buttons to prevent multiple clicks while waiting for response
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        // Set wait cursor while waiting for response
        setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));

        PatientService.getInstance()
            .createPatientAsync(patient)
            .orTimeout(10, java.util.concurrent.TimeUnit.SECONDS)
            .whenComplete((result, ex) -> {

                javax.swing.SwingUtilities.invokeLater(() ->{

                    // Restore cursor and buttons
                    setCursor(java.awt.Cursor.getDefaultCursor());
                    jButton1.setEnabled(true);
                    jButton2.setEnabled(true);

                    if (ex != null) {
                        JOptionPane.showMessageDialog(this, "Error creating patient: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    } else if (result.isSuccess()) {
                        Patient[] patients = result.getData();
                        panel.addPatient(patients[0]);
                        JOptionPane.showMessageDialog(this, "Successfully created patient!", "Success", JOptionPane.INFORMATION_MESSAGE);
                        dispose(); // Close the frame only on success
                    } else {
                        JOptionPane.showMessageDialog(this, "Error creating patient: " + result.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                });
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.group_13.ui.PatientDataPanel patientDataPanel1;
    // End of variables declaration//GEN-END:variables
}
