/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group_13.ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.group_13.model.*;
import com.group_13.service.PatientService;
import com.group_13.service.RecordService;

/**
 *
 * @author JONIK
 */
public class PatientModifyFrame extends javax.swing.JFrame {


        /**
         * Creates new form PatientModifyFrame
         */
        private Patient patient;
        private PatientPanel panel;

        public PatientModifyFrame(PatientPanel panel, Patient patient) {
                super();
                this.patient = patient;
                initComponents();
                setTitle("View/Update patient data");
                setLocationRelativeTo(null);
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                patientDataPanel1.setPatientData(patient);

                // Modify button
                jButton1.addActionListener(e -> {
                        try {
                                jButton1ActionPerformed(e);
                        } catch (Exception g) {
                                // TODO Auto-generated catch block
                                g.printStackTrace();
                        }
                });

                // Exit button
                jButton2.addActionListener(e -> {
                        jButton2ActionPerformed(e);
                });
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jTextField1 = new javax.swing.JTextField();
                patientDataPanel1 = new com.group_13.ui.PatientDataPanel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));

                jTextField1.setText("jTextField1");

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setPreferredSize(new java.awt.Dimension(500, 500));

                jButton1.setText("Update patient data");

                jButton2.setText("Cancel");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(patientDataPanel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                555,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jButton1)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton2)))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(patientDataPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                231,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                71,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButton1)
                                                                                .addComponent(jButton2))
                                                                .addContainerGap()));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {// GEN-FIRST:event_jButton1ActionPerformed
                patientDataPanel1.updatePatientData(patient);
                Result<Void> result = PatientService.getInstance().updatePatient(patient);
                if (result.isSuccess()) {
                        panel.updatePatient(patient); // Refresh patient data in PatientPanel
                        JOptionPane.showMessageDialog(this, "Patient updated successfully!", "Success",
                                        JOptionPane.INFORMATION_MESSAGE);
                } else {
                        JOptionPane.showMessageDialog(this, "Failed to update patient", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
                dispose();
        }// GEN-LAST:event_jButton1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
                dispose();
        }// GEN-LAST:event_jButton2ActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField jTextField1;
        private com.group_13.ui.PatientDataPanel patientDataPanel1;
        // End of variables declaration//GEN-END:variables
}
