/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group_13.ui;

import com.group_13.model.Patient;
import com.group_13.model.Record;
import com.group_13.service.PatientService;
import com.group_13.service.RecordService;
import com.group_13.model.Result;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JONIK
 */
public class RecordCreateFrame extends javax.swing.JFrame {

    private final Patient patient;
    private Record record;
    private RecordPanel panel;

    /**
     * Creates new form RecordCreateFrame
     * 
     * @param patient
     */
    public RecordCreateFrame(RecordPanel panel, Patient patient) {
        this.panel = panel;
        this.patient = patient;
        initComponents();
        setTitle("Create new record");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recordDataPanel1 = new com.group_13.ui.RecordDataPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jButton1.setText("Create record");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Cancel");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(recordDataPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(recordDataPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        // Create new patient object with form data
        record = new Record();
        recordDataPanel1.updateRecordData(record, patient);

        // disable buttons to prevent multiple clicks while waiting for response
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        // Set wait cursor while waiting for response
        setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));

        RecordService.getInstance()
                .createRecordAsync(record)
                .orTimeout(10, java.util.concurrent.TimeUnit.SECONDS)
                .whenComplete((result, ex) -> {

                    javax.swing.SwingUtilities.invokeLater(() -> {

                        // Restore cursor and buttons
                        setCursor(java.awt.Cursor.getDefaultCursor());
                        jButton1.setEnabled(true);
                        jButton2.setEnabled(true);

                        if (ex != null) {
                            JOptionPane.showMessageDialog(this, "Error creating record: " + ex.getMessage(), "Error",
                                    JOptionPane.ERROR_MESSAGE);
                        } else if (result.isSuccess()) {
                            Record[] records = result.getData();
                            panel.addRecord(records[0]);
                            JOptionPane.showMessageDialog(this, "Successfully created record!", "Success",
                                    JOptionPane.INFORMATION_MESSAGE);
                            dispose(); // Close the frame only on success
                        } else {
                            JOptionPane.showMessageDialog(this, "Error creating record: " + result.getMessage(),
                                    "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    });
                });
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }// GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.group_13.ui.RecordDataPanel recordDataPanel1;
    // End of variables declaration//GEN-END:variables
}
