/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.group_13.ui;

import java.util.*;
import com.group_13.model.Record;
import com.group_13.model.Patient;
import com.group_13.model.RecordTable;
import javax.swing.JOptionPane;

import com.group_13.service.RecordService;
import com.group_13.model.Result;

/**
 *
 * @author JONIK
 */
public class RecordPanel extends javax.swing.JPanel {

    private RecordTable model = new RecordTable(); // This contains the table data
    private Patient patient; // Store selected patient
    private Record record; // Store selected record

    private static RecordPanel INSTANCE;

    public static synchronized RecordPanel getInstance() {
        if (INSTANCE == null) {
            INSTANCE = new RecordPanel();
        }
        return INSTANCE;
    }

    /**
     * Creates new form RecordPanel
     */
    private RecordPanel() {
        initComponents();
        jTable1.setModel(model);

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2 && jTable1.getSelectedRow() != -1) {
                    int row = jTable1.getSelectedRow();
                    record = model.getRecord(row);
                    openRecordModifyFrame(record, patient);
                }
            }
        });

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 1 && jTable1.getSelectedRow() != -1) {
                    int row = jTable1.getSelectedRow();
                    record = model.getRecord(row);
                }
            }
        });
    }

    public void showRecordsForPatient(Patient patient) {
        this.patient = patient;
        try {
            Result<Record[]> result = RecordService.getInstance().getRecordsByPatientId(patient);
            if (result.isSuccess()) {
                model.setRecords(Arrays.asList(result.getData()));
                System.out.println("Successfully fetched " + result.getData().length + " records for patient: " + patient.getFName() + " " + patient.getLName() + ", ID: " + patient.getId());
            } else {
                System.out.println("Error fetching records for patient");
            }
        } catch (Exception e) {
            System.out.println("Error fetching records for patient: " + e.getMessage());
        }
    }

    private void openRecordModifyFrame(Record record, Patient patient) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            RecordModifyFrame frame = new RecordModifyFrame(record, patient);
            frame.setVisible(true);
        });
    }

    public void clearSelection() {
        this.record = null;
    }

    public void passQueryResults(Record[] recordlist) {
        if (recordlist == null) {
            model.setRecords(Collections.emptyList());
            return;
        }
        List<Record> list = Arrays.asList(recordlist);
        model.setRecords(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Create new record");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Delete record");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton1.setText("Search records");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Modify record");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627,
                                                Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton4)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3)
                                        .addComponent(jButton4)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        if (patient == null) {
            // no patient selected
            JOptionPane.showMessageDialog(this,
                    "Please select a patient for whom to create a record.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.SwingUtilities.invokeLater(() -> {
            RecordCreateFrame frame = new RecordCreateFrame(patient);
            frame.setVisible(true);
        });
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        javax.swing.SwingUtilities.invokeLater(() -> {
            RecordSearchFrame frame = new RecordSearchFrame(patient);
            frame.setVisible(true);
        });
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        if (record == null) {
            // no record selected
            JOptionPane.showMessageDialog(this,
                    "Please select a record to update.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.SwingUtilities.invokeLater(() -> {
            RecordModifyFrame frame = new RecordModifyFrame(record, patient);
            frame.setVisible(true);
        });
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        if (record == null) {
            // No patient selected
            JOptionPane.showMessageDialog(this,
                    "Please select a record to delete.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete record of " + patient.getFName() + " " + patient.getLName() + "?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                RecordService.getInstance().deleteRecord(record);
                model.deleteRecord(record);
                clearSelection();
                JOptionPane.showMessageDialog(this,
                        "Record deleted successfully.",
                        "Deleted",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error deleting record: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
